on:
  push:
    tags:
      - "v*"
name: "Build & Release"
jobs:
  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: "gradle"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk --split-per-abi

      - uses: actions/upload-artifact@v3
        with:
          name: "android-artifact"
          path: "build/app/outputs/apk/release/*.apk"

  release:
    name: Release collected artifacts
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/android-artifact/*.apk"
          tag: ${{ steps.get_version.outputs.VERSION }}
          token: ${{ secrets.TOKEN }}
